plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':boss-interfaces')

    // 版本由根 build.gradle 的 dependencyManagement 统一管理
    implementation 'com.xs.xsbox:xsbox-spring-boot-starter'

    // Vavr 函数式编程库
    implementation 'io.vavr:vavr:0.10.4'

    // 开发工具
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // 测试
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    mainClass = 'com.xs.boss.start.StartApplication'
}

processResources {
    filesMatching(['**/*.yml', '**/*.properties', '**/*.md']) {
        expand(project.properties)
    }
}

