spring:
  application:
    name: order-service
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://rm-uf639588047126dlb.mysql.rds.aliyuncs.com:3306/fom_sit?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8mb4&allowPublicKeyRetrieval=true
    username: fom_sit
    password: w1aVKzdmXKZEbJjE
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: r-uf6jgm7mhg9bpfcrql.redis.rds.aliyuncs.com
      port: 6379
      password: crm_nonpro:R4QbjTrK5UyZPKpU
      database: 17
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: 2000ms

  kafka:
    bootstrap-servers: kafka.sit.eainc.com:9092
    client-id: order-service-client
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      compression-type: lz4
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
    admin:
      fail-fast: true
    template:
      default-topic: order-service-test

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xs.order.service.domain.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.xs.order.service.infrastructure.persistence.mapper: DEBUG

server:
  port: 8080
# redis cluster & kafka cluster configured
