plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':order-service-interfaces')

    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // 数据访问（需要用于 @MapperScan 注解）
    implementation 'com.baomidou:mybatis-plus-spring-boot3-starter'

    // 开发工具
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // 测试
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    mainClass = 'com.xs.order.OrderServiceApplication'
}

processResources {
    filesMatching(['**/*.yml', '**/*.properties', '**/*.md']) {
        expand(project.properties)
    }
}
